// GENERATED by scripts/generate-statements.mjs from FinchNode public demo records. Do not edit by hand.
// Re-run `node scripts/generate-statements.mjs` (or --check) after changing src/services/billing/recipes.ts.
export interface GeneratedStatement {
  subject: string;
  serviceDate: string;
  encounter: { id: string; type: string };
  invoice: string;
  total: number;
  statement: string;
  lines: Array<{ description: string; code: string; amount: number; unsupported: boolean; evidence: Array<{ id: string; category: string; name: string }> }>;
}

export const generatedStatements: Record<string, GeneratedStatement> = {
  "morgan-wellness": {
    "subject": "patient-demo-001",
    "serviceDate": "2026-07-18",
    "encounter": {
      "id": "rec_1caa8ec82b5aed3c83bc1f46",
      "type": "Annual wellness visit"
    },
    "invoice": "NS-71802",
    "total": 1102,
    "lines": [
      {
        "description": "Annual wellness visit, established patient",
        "code": "99395",
        "amount": 425,
        "unsupported": false,
        "evidence": [
          {
            "id": "rec_1caa8ec82b5aed3c83bc1f46",
            "category": "encounters",
            "name": "Annual wellness visit"
          }
        ]
      },
      {
        "description": "Metabolic monitoring panel",
        "code": "80048",
        "amount": 118,
        "unsupported": false,
        "evidence": [
          {
            "id": "rec_825b22849e5d96a98ccfc0bc",
            "category": "labs",
            "name": "Glucose"
          },
          {
            "id": "rec_f458f7825d1f184df3e47fee",
            "category": "labs",
            "name": "Creatinine"
          },
          {
            "id": "rec_40ce30412de9daddce03fd67",
            "category": "labs",
            "name": "Potassium"
          },
          {
            "id": "rec_7ea9e3f7b05f6cdb6bef7dd6",
            "category": "diagnosticReports",
            "name": "Synthetic metabolic monitoring panel"
          }
        ]
      },
      {
        "description": "Hemoglobin A1c",
        "code": "83036",
        "amount": 94,
        "unsupported": false,
        "evidence": [
          {
            "id": "rec_e7684bfafc242aedaaed7a68",
            "category": "labs",
            "name": "Hemoglobin A1c"
          }
        ]
      },
      {
        "description": "LDL cholesterol",
        "code": "83721",
        "amount": 82,
        "unsupported": false,
        "evidence": [
          {
            "id": "rec_1df53aed4ceb6365aa76efbb",
            "category": "labs",
            "name": "LDL cholesterol"
          }
        ]
      },
      {
        "description": "Hemoglobin",
        "code": "85018",
        "amount": 41,
        "unsupported": false,
        "evidence": [
          {
            "id": "rec_d29022a9a97f645be711d0f7",
            "category": "labs",
            "name": "Hemoglobin"
          }
        ]
      },
      {
        "description": "Metformin 500 mg tablet, administered at visit",
        "code": "99070",
        "amount": 32,
        "unsupported": false,
        "evidence": [
          {
            "id": "rec_a81e05c4c049bf549c1e4fc5",
            "category": "medications",
            "name": "Metformin 500 mg tablet"
          },
          {
            "id": "rec_9f610c7710d2b5ed95494c48",
            "category": "medicationAdministrations",
            "name": "Metformin 500 mg tablet"
          }
        ]
      },
      {
        "description": "Electrocardiogram, 12-lead",
        "code": "93000",
        "amount": 310,
        "unsupported": true,
        "evidence": []
      }
    ],
    "statement": "Invoice: NS-71802\nProvider: Northstar Health System\nService date: 2026-07-18\nInsurance adjustments: 0.00\nPatient responsibility: 1102.00\nCharges\nAnnual wellness visit, established patient | 99395 | 425.00\nMetabolic monitoring panel | 80048 | 118.00\nHemoglobin A1c | 83036 | 94.00\nLDL cholesterol | 83721 | 82.00\nHemoglobin | 85018 | 41.00\nMetformin 500 mg tablet, administered at visit | 99070 | 32.00\nElectrocardiogram, 12-lead | 93000 | 310.00\nTotal: 1102.00"
  },
  "harriet-kidney": {
    "subject": "patient-demo-polypharmacy",
    "serviceDate": "2026-01-20",
    "encounter": {
      "id": "rec_85953451af7689f018656bf8",
      "type": "Primary care follow-up"
    },
    "invoice": "NS-58417",
    "total": 964,
    "lines": [
      {
        "description": "Primary care follow-up visit, established patient",
        "code": "99214",
        "amount": 310,
        "unsupported": false,
        "evidence": [
          {
            "id": "rec_85953451af7689f018656bf8",
            "category": "encounters",
            "name": "Primary care follow-up"
          }
        ]
      },
      {
        "description": "Renal function panel",
        "code": "80069",
        "amount": 112,
        "unsupported": false,
        "evidence": [
          {
            "id": "rec_84ba2b3344297f4af6feb417",
            "category": "labs",
            "name": "Creatinine [Mass/volume] in Serum or Plasma"
          },
          {
            "id": "rec_fc8a3b45c6f176dd12b6c72d",
            "category": "labs",
            "name": "Glomerular filtration rate [Volume Rate/Area] in Serum, Plasma or Blood by Creatinine-based formula (CKD-EPI 2021)/1.73 sq M"
          },
          {
            "id": "rec_f7b4b1dbcf95170a33dc59d3",
            "category": "labs",
            "name": "Urea nitrogen [Mass/volume] in Serum or Plasma"
          },
          {
            "id": "rec_3136b32083e3a3f018727339",
            "category": "diagnosticReports",
            "name": "Kidney function draw (creatinine, eGFR, potassium, sodium, BUN)"
          }
        ]
      },
      {
        "description": "Hemoglobin A1c",
        "code": "83036",
        "amount": 94,
        "unsupported": false,
        "evidence": [
          {
            "id": "rec_57589e8bb4bd9740c4daf912",
            "category": "labs",
            "name": "Hemoglobin A1c/Hemoglobin.total in Blood"
          }
        ]
      },
      {
        "description": "Lipid panel",
        "code": "80061",
        "amount": 128,
        "unsupported": false,
        "evidence": [
          {
            "id": "rec_54093577def5dbf599255bef",
            "category": "labs",
            "name": "Cholesterol in LDL [Mass/volume] in Serum or Plasma by calculation"
          },
          {
            "id": "rec_5894b13d943ee561418a7271",
            "category": "labs",
            "name": "Cholesterol in HDL [Mass/volume] in Serum or Plasma"
          },
          {
            "id": "rec_f114ae78dec4dc67a114e0bf",
            "category": "labs",
            "name": "Triglyceride [Mass/volume] in Serum or Plasma"
          }
        ]
      },
      {
        "description": "Thyroid stimulating hormone (TSH)",
        "code": "84443",
        "amount": 86,
        "unsupported": false,
        "evidence": [
          {
            "id": "rec_d7187962c23560d6c311c752",
            "category": "labs",
            "name": "Thyrotropin [Units/volume] in Serum or Plasma"
          }
        ]
      },
      {
        "description": "Venipuncture, blood draw",
        "code": "36415",
        "amount": 24,
        "unsupported": false,
        "evidence": [
          {
            "id": "rec_3136b32083e3a3f018727339",
            "category": "diagnosticReports",
            "name": "Kidney function draw (creatinine, eGFR, potassium, sodium, BUN)"
          }
        ]
      },
      {
        "description": "Electrocardiogram, 12-lead",
        "code": "93000",
        "amount": 210,
        "unsupported": true,
        "evidence": []
      }
    ],
    "statement": "Invoice: NS-58417\nProvider: Northstar Health System\nService date: 2026-01-20\nInsurance adjustments: 0.00\nPatient responsibility: 964.00\nCharges\nPrimary care follow-up visit, established patient | 99214 | 310.00\nRenal function panel | 80069 | 112.00\nHemoglobin A1c | 83036 | 94.00\nLipid panel | 80061 | 128.00\nThyroid stimulating hormone (TSH) | 84443 | 86.00\nVenipuncture, blood draw | 36415 | 24.00\nElectrocardiogram, 12-lead | 93000 | 210.00\nTotal: 964.00"
  },
  "theo-asthma": {
    "subject": "patient-demo-pediatric-asthma",
    "serviceDate": "2025-03-22",
    "encounter": {
      "id": "rec_648d032468d74cfe14eb6c49",
      "type": "Asthma follow-up"
    },
    "invoice": "NS-33096",
    "total": 507,
    "lines": [
      {
        "description": "Asthma follow-up visit, established patient",
        "code": "99214",
        "amount": 275,
        "unsupported": false,
        "evidence": [
          {
            "id": "rec_648d032468d74cfe14eb6c49",
            "category": "encounters",
            "name": "Asthma follow-up"
          }
        ]
      },
      {
        "description": "Pulse oximetry",
        "code": "94760",
        "amount": 38,
        "unsupported": false,
        "evidence": [
          {
            "id": "rec_4aedd4b5bf290c9f46531b40",
            "category": "vitals",
            "name": "Oxygen saturation in Arterial blood by Pulse oximetry"
          }
        ]
      },
      {
        "description": "Inhaler technique evaluation",
        "code": "94664",
        "amount": 64,
        "unsupported": false,
        "evidence": [
          {
            "id": "rec_471ec501ebab480f51a12fca",
            "category": "medications",
            "name": "NDA021457 200 ACTUAT albuterol 0.09 MG/ACTUAT Metered Dose Inhaler"
          },
          {
            "id": "rec_775653dd34d652e1a893305e",
            "category": "medications",
            "name": "120 ACTUAT fluticasone propionate 0.044 MG/ACTUAT Metered Dose Inhaler"
          }
        ]
      },
      {
        "description": "Albuterol inhaler, clinic-supplied",
        "code": "99070",
        "amount": 58,
        "unsupported": false,
        "evidence": [
          {
            "id": "rec_471ec501ebab480f51a12fca",
            "category": "medications",
            "name": "NDA021457 200 ACTUAT albuterol 0.09 MG/ACTUAT Metered Dose Inhaler"
          }
        ]
      },
      {
        "description": "Fluticasone inhaler, clinic-supplied",
        "code": "99070",
        "amount": 72,
        "unsupported": false,
        "evidence": [
          {
            "id": "rec_775653dd34d652e1a893305e",
            "category": "medications",
            "name": "120 ACTUAT fluticasone propionate 0.044 MG/ACTUAT Metered Dose Inhaler"
          }
        ]
      }
    ],
    "statement": "Invoice: NS-33096\nProvider: Northstar Health System\nService date: 2025-03-22\nInsurance adjustments: 0.00\nPatient responsibility: 507.00\nCharges\nAsthma follow-up visit, established patient | 99214 | 275.00\nPulse oximetry | 94760 | 38.00\nInhaler technique evaluation | 94664 | 64.00\nAlbuterol inhaler, clinic-supplied | 99070 | 58.00\nFluticasone inhaler, clinic-supplied | 99070 | 72.00\nTotal: 507.00"
  }
};
