// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  ExternalMedicalRecord,
} from "./types";

export default {
  ownerIdentity: __t.identity(),
  transactionId: __t.string(),
  merchant: __t.string(),
  amountCents: __t.i64(),
  paidOn: __t.string(),
  transactionSource: __t.string(),
  recordsSource: __t.string(),
  get records() {
    return __t.array(ExternalMedicalRecord);
  },
};
