// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  caseId: __t.u64().name("case_id"),
  owner: __t.identity(),
  description: __t.string(),
  code: __t.option(__t.string()),
  amountCents: __t.i64().name("amount_cents"),
  serviceDate: __t.string().name("service_date"),
});
