// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Resolution,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  label: __t.string(),
  status: __t.string(),
  transactionId: __t.string().name("transaction_id"),
  merchant: __t.string(),
  amountCents: __t.i64().name("amount_cents"),
  paidOn: __t.string().name("paid_on"),
  invoiceId: __t.option(__t.string()).name("invoice_id"),
  billTotalCents: __t.option(__t.i64()).name("bill_total_cents"),
  get resolution() {
    return __t.option(Resolution);
  },
  summary: __t.option(__t.string()),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
