// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  caseId: __t.u64().name("case_id"),
  owner: __t.identity(),
  billItemId: __t.option(__t.u64()).name("bill_item_id"),
  description: __t.string(),
  amountCents: __t.i64().name("amount_cents"),
  clinicalStatus: __t.string().name("clinical_status"),
  pricingStatus: __t.string().name("pricing_status"),
  confidence: __t.f64(),
  evidence: __t.array(__t.string()),
  explanation: __t.string(),
  action: __t.string(),
});
