// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  caseId: __t.u64().primaryKey().name("case_id"),
  owner: __t.identity(),
  payer: __t.string(),
  plan: __t.string(),
  network: __t.string(),
  claimStatus: __t.string().name("claim_status"),
  synthetic: __t.bool(),
  billedCents: __t.i64().name("billed_cents"),
  allowedCents: __t.i64().name("allowed_cents"),
  contractualCents: __t.i64().name("contractual_cents"),
  insurerPaidCents: __t.i64().name("insurer_paid_cents"),
  deductibleCents: __t.i64().name("deductible_cents"),
  copayCents: __t.i64().name("copay_cents"),
  coinsuranceCents: __t.i64().name("coinsurance_cents"),
  noncoveredCents: __t.i64().name("noncovered_cents"),
  patientResponsibilityCents: __t.i64().name("patient_responsibility_cents"),
  possibleOverpaymentCents: __t.i64().name("possible_overpayment_cents"),
  status: __t.string(),
  notes: __t.array(__t.string()),
});
