// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  caseId: __t.u64().name("case_id"),
  owner: __t.identity(),
  billItemId: __t.u64().name("bill_item_id"),
  referenceCents: __t.i64().name("reference_cents"),
  comparedCents: __t.i64().name("compared_cents"),
  comparedField: __t.string().name("compared_field"),
  multiple: __t.f64(),
  basis: __t.string(),
  sourceName: __t.string().name("source_name"),
  sourceUrl: __t.string().name("source_url"),
  asOf: __t.string().name("as_of"),
  review: __t.bool(),
});
