// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AuditEntry = __t.object("AuditEntry", {
  id: __t.u64(),
  caseId: __t.u64(),
  owner: __t.identity(),
  at: __t.timestamp(),
  action: __t.string(),
  tool: __t.string(),
  inputSummary: __t.string(),
  outputSummary: __t.string(),
  status: __t.string(),
});
export type AuditEntry = __Infer<typeof AuditEntry>;

export const BillCase = __t.object("BillCase", {
  id: __t.u64(),
  owner: __t.identity(),
  label: __t.string(),
  status: __t.string(),
  transactionId: __t.string(),
  merchant: __t.string(),
  amountCents: __t.i64(),
  paidOn: __t.string(),
  invoiceId: __t.option(__t.string()),
  billTotalCents: __t.option(__t.i64()),
  get resolution() {
    return __t.option(Resolution);
  },
  summary: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type BillCase = __Infer<typeof BillCase>;

export const BillDelivery = __t.object("BillDelivery", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  caseId: __t.u64(),
});
export type BillDelivery = __Infer<typeof BillDelivery>;

export const BillItem = __t.object("BillItem", {
  id: __t.u64(),
  caseId: __t.u64(),
  owner: __t.identity(),
  description: __t.string(),
  code: __t.option(__t.string()),
  amountCents: __t.i64(),
  serviceDate: __t.string(),
});
export type BillItem = __Infer<typeof BillItem>;

export const Communication = __t.object("Communication", {
  id: __t.u64(),
  caseId: __t.u64(),
  owner: __t.identity(),
  kind: __t.string(),
  at: __t.timestamp(),
  status: __t.string(),
  transcript: __t.string(),
  result: __t.option(__t.string()),
  messageId: __t.option(__t.string()),
});
export type Communication = __Infer<typeof Communication>;

export const ExternalMedicalRecord = __t.object("ExternalMedicalRecord", {
  kind: __t.string(),
  description: __t.string(),
  date: __t.string(),
  provider: __t.string(),
});
export type ExternalMedicalRecord = __Infer<typeof ExternalMedicalRecord>;

export const Finding = __t.object("Finding", {
  id: __t.u64(),
  caseId: __t.u64(),
  owner: __t.identity(),
  billItemId: __t.option(__t.u64()),
  description: __t.string(),
  amountCents: __t.i64(),
  clinicalStatus: __t.string(),
  pricingStatus: __t.string(),
  confidence: __t.f64(),
  evidence: __t.array(__t.string()),
  explanation: __t.string(),
  action: __t.string(),
});
export type Finding = __Infer<typeof Finding>;

export const InsuranceSummary = __t.object("InsuranceSummary", {
  caseId: __t.u64(),
  owner: __t.identity(),
  payer: __t.string(),
  plan: __t.string(),
  network: __t.string(),
  claimStatus: __t.string(),
  synthetic: __t.bool(),
  billedCents: __t.i64(),
  allowedCents: __t.i64(),
  contractualCents: __t.i64(),
  insurerPaidCents: __t.i64(),
  deductibleCents: __t.i64(),
  copayCents: __t.i64(),
  coinsuranceCents: __t.i64(),
  noncoveredCents: __t.i64(),
  patientResponsibilityCents: __t.i64(),
  possibleOverpaymentCents: __t.i64(),
  status: __t.string(),
  notes: __t.array(__t.string()),
});
export type InsuranceSummary = __Infer<typeof InsuranceSummary>;

export const MedicalRecord = __t.object("MedicalRecord", {
  id: __t.u64(),
  caseId: __t.u64(),
  owner: __t.identity(),
  kind: __t.string(),
  description: __t.string(),
  date: __t.string(),
  provider: __t.string(),
});
export type MedicalRecord = __Infer<typeof MedicalRecord>;

export const ModuleOwner = __t.object("ModuleOwner", {
  ownerIdentity: __t.identity(),
});
export type ModuleOwner = __Infer<typeof ModuleOwner>;

export const MyAuditLog = __t.object("MyAuditLog", {});
export type MyAuditLog = __Infer<typeof MyAuditLog>;

export const MyBillItems = __t.object("MyBillItems", {});
export type MyBillItems = __Infer<typeof MyBillItems>;

export const MyCases = __t.object("MyCases", {});
export type MyCases = __Infer<typeof MyCases>;

export const MyCommunications = __t.object("MyCommunications", {});
export type MyCommunications = __Infer<typeof MyCommunications>;

export const MyFindings = __t.object("MyFindings", {});
export type MyFindings = __Infer<typeof MyFindings>;

export const MyInsurance = __t.object("MyInsurance", {});
export type MyInsurance = __Infer<typeof MyInsurance>;

export const MyMedicalRecords = __t.object("MyMedicalRecords", {});
export type MyMedicalRecords = __Infer<typeof MyMedicalRecords>;

export const MyPriceComparisons = __t.object("MyPriceComparisons", {});
export type MyPriceComparisons = __Infer<typeof MyPriceComparisons>;

export const MyTimeline = __t.object("MyTimeline", {});
export type MyTimeline = __Infer<typeof MyTimeline>;

export const OutboundAttempt = __t.object("OutboundAttempt", {
  communicationId: __t.u64(),
  attempts: __t.u32(),
  lastError: __t.string(),
});
export type OutboundAttempt = __Infer<typeof OutboundAttempt>;

export const PriceComparison = __t.object("PriceComparison", {
  id: __t.u64(),
  caseId: __t.u64(),
  owner: __t.identity(),
  billItemId: __t.u64(),
  referenceCents: __t.i64(),
  comparedCents: __t.i64(),
  comparedField: __t.string(),
  multiple: __t.f64(),
  basis: __t.string(),
  sourceName: __t.string(),
  sourceUrl: __t.string(),
  asOf: __t.string(),
  review: __t.bool(),
});
export type PriceComparison = __Infer<typeof PriceComparison>;

export const ProcessedEmail = __t.object("ProcessedEmail", {
  messageId: __t.string(),
  caseId: __t.u64(),
  kind: __t.string(),
});
export type ProcessedEmail = __Infer<typeof ProcessedEmail>;

export const Resolution = __t.object("Resolution", {
  result: __t.string(),
  originalTotalCents: __t.i64(),
  correctedTotalCents: __t.i64(),
  adjustmentCents: __t.i64(),
  explanation: __t.string(),
});
export type Resolution = __Infer<typeof Resolution>;

export const TimelineEvent = __t.object("TimelineEvent", {
  id: __t.u64(),
  caseId: __t.u64(),
  owner: __t.identity(),
  at: __t.timestamp(),
  title: __t.string(),
  detail: __t.string(),
  source: __t.string(),
  status: __t.string(),
});
export type TimelineEvent = __Infer<typeof TimelineEvent>;

