// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AuthorizeReviewReducer from "../authorize_review_reducer";
import InvestigateCaseReducer from "../investigate_case_reducer";
import ResetDemoReducer from "../reset_demo_reducer";
import ScanDemoPaymentReducer from "../scan_demo_payment_reducer";

export type AuthorizeReviewParams = __Infer<typeof AuthorizeReviewReducer>;
export type InvestigateCaseParams = __Infer<typeof InvestigateCaseReducer>;
export type ResetDemoParams = __Infer<typeof ResetDemoReducer>;
export type ScanDemoPaymentParams = __Infer<typeof ScanDemoPaymentReducer>;

