export type CaseStatus = "DETECTED" | "FETCHING_RECORDS" | "REQUESTING_BILL" | "WAITING_FOR_BILL" | "ANALYZING" | "REVIEW_REQUIRED" | "CONTACTING_PROVIDER" | "WAITING_FOR_PROVIDER" | "RESOLVED" | "USER_NOTIFIED" | "FAILED";
export type ClinicalStatus = "SUPPORTED" | "PARTIALLY_SUPPORTED" | "NO_MATCH_FOUND" | "DUPLICATE_SUSPECTED" | "DATE_MISMATCH" | "AMOUNT_REVIEW" | "INSUFFICIENT_DATA";

export interface Transaction { id: string; merchant: string; amount: number; date: string; category?: string }
export interface MedicalRecord { id: string; type: "encounter" | "imaging" | "procedure" | "medication" | "lab" | "document"; description: string; date: string; provider: string }
export interface BillItem { id: string; description: string; code?: string; amount: number; serviceDate: string; units?: number; setting?: "INPATIENT" | "OUTPATIENT"; component?: "FACILITY" | "PROFESSIONAL" | "GLOBAL"; modifiers?: string[] }
export interface ItemizedBill { invoiceId: string; provider: string; total: number; patientResponsibility?: number; insuranceAdjustments?: number; items: BillItem[] }
export interface ExplanationOfBenefits { invoiceId: string; serviceDate: string; billedTotal: number; allowedTotal: number; contractualAdjustment: number; insurerPaid: number; otherPayerPaid: number; deductible: number; copay: number; coinsurance: number; noncovered: number; patientResponsibility: number }
export interface InsuranceContext { coverage: "SELF_PAY" | "INSURED" | "UNKNOWN"; network: "IN_NETWORK" | "OUT_OF_NETWORK" | "UNKNOWN"; claimStatus: "FINAL" | "PENDING" | "DENIED" | "UNKNOWN"; payer?: string; plan?: string; eob?: ExplanationOfBenefits }
export interface FinancialReview { status: "NEEDS_INFORMATION" | "CLAIM_PENDING" | "REVIEW_REQUIRED" | "RECONCILED" | "REPROCESSING_REQUIRED"; expectedPatientResponsibility?: number; possibleExcessPayment?: number; reasons: string[] }
export interface PriceComparison { referenceAmount: number; multiple: number; sourceName: string; sourceUrl: string; basis: "CASH" | "NEGOTIATED" | "MEDICARE"; asOf: string }
export interface Finding { billItemId: string; description: string; amount: number; clinicalStatus: ClinicalStatus; pricingStatus: "NOT_ASSESSED" | "ASSESSED" | "REVIEW"; priceComparison?: PriceComparison; confidence: number; evidence: string[]; evidenceRecordIds?: string[]; explanation: string; action: "NONE" | "REQUEST_REVIEW" }
export interface TimelineEvent { id: string; timestamp: string; title: string; detail: string; source: string; status: "complete" | "attention" | "pending" }
export interface AuditEntry { id: string; timestamp: string; action: string; tool: string; inputSummary: string; outputSummary: string; status: "SUCCESS" | "FAILED" }
export interface Communication { id: string; type: "ITEMIZED_BILL_REQUEST" | "BILLING_REVIEW" | "USER_NOTIFICATION"; timestamp: string; status: "COMPLETED" | "PENDING"; transcript: string; result?: string }
export interface Resolution { result: "DUPLICATE_REMOVED" | "CHARGE_VERIFIED" | "PROVIDER_REVIEW_PENDING" | "UNRESOLVED"; originalTotal: number; correctedTotal: number; adjustment: number; explanation: string }
export interface Recovery { status: "REFUND_PENDING" | "REFUND_RECEIVED"; amount: number; confirmation: string; creditTransactionId?: string; simulated: boolean }
export interface MedicalBillCase { id: string; status: CaseStatus; transaction: Transaction; provider: { name: string }; medicalRecords: MedicalRecord[]; bill: ItemizedBill | null; findings: Finding[]; insurance?: InsuranceContext; financialReview?: FinancialReview; communications: Communication[]; timeline: TimelineEvent[]; auditLog: AuditEntry[]; resolution: Resolution | null; recovery?: Recovery; summary: string | null; createdAt: string; updatedAt: string }
