#!/usr/bin/env python3
"""Generates spacetimedb/src/logic/price-references.ts from the committed UM Health snapshot.

Keeps only real dollar rates: "fee schedule" negotiated rates and "discounted cash" prices
(a percent-of-billed-charges row's dollar figure is an estimate). Duplicate rows are removed so a
unique match is not mistaken for an ambiguous one. Reducers cannot read files, hence a TS table.
"""
import json, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
catalog = json.loads((root / "reference-data/michigan-medicine-selected-rates.json").read_text())
seen, rows = set(), []
for r in catalog["records"]:
    basis = "CASH" if r["basis"] == "CASH" and r["methodology"] == "discounted cash" else "NEGOTIATED" if r["basis"] == "NEGOTIATED" and r["methodology"] == "fee schedule" else None
    if not basis or not isinstance(r.get("amount"), (int, float)) or r["amount"] <= 0: continue
    if r["setting"] not in ("INPATIENT", "OUTPATIENT") or r["component"] not in ("FACILITY", "PROFESSIONAL", "GLOBAL"): continue
    mods = sorted(m for m in r["modifiers"].replace("|", " ").replace(",", " ").replace(";", " ").split() if m)
    for c in r["codes"]:
        row = {"code": c["code"], "basis": basis, "payer": r["payer"] or "", "plan": r["plan"] or "", "setting": r["setting"], "component": r["component"], "modifiers": mods, "units": r["units"] or 1, "amountCents": round(r["amount"] * 100)}
        key = json.dumps(row, sort_keys=True)
        if key in seen: continue
        seen.add(key); rows.append(row)
m, d, y = (int(x) for x in catalog["records"][0]["asOf"].split("/"))
source = {"provider": catalog["records"][0]["provider"], "name": catalog["sourceName"], "url": catalog["sourceUrl"], "asOf": f"{y:04d}-{m:02d}-{d:02d}", "retrievedOn": catalog["retrievedOn"]}
out = root / "spacetimedb/src/logic/price-references.ts"
out.write_text(
    "// Generated by scripts/build-price-references.py from reference-data/michigan-medicine-selected-rates.json. Do not edit.\n"
    "import type { PriceRate, PriceSource } from \"./types\";\n\n"
    f"export const PRICE_SOURCE: PriceSource = {json.dumps(source)};\n\n"
    f"export const PRICE_RATES: PriceRate[] = {json.dumps(rows, separators=(',', ':'))};\n"
)
print(f"wrote {len(rows)} rates to {out.relative_to(root)}")
